#!/bin/bash

domd5 () {

echo "$1" | md5sum | awk '{print $1}'

}

make_thumbnail () {

WIDTH=$(identify -format '%w' "$1")
HEIGHT=$(identify -format '%h' "$1")

RESIZE_OPTION="-resize 512"
if [ "$HEIGHT" -gt "$WIDTH" ]; then
	RESIZE_OPTION="-geometry x512"
fi

convert "$1" $RESIZE_OPTION -background 'rgba(0,0,0,0)' -gravity center -extent 512x512 "$2"

}

mkdir -p _db
mkdir -p assets/screenshots/thumb

for file in $(find assets/screenshots -maxdepth 1 -iname *.png); do
	BASE=${file##*/}
	if [ ! -f "assets/screenshots/thumb/$BASE" ]; then
		echo Thumbnailing $BASE
		make_thumbnail "$file" "assets/screenshots/thumb/$BASE"
	fi
done

for file in $(find assets -iname *.png); do
	MD5=$(domd5 "$file")
	FILE_MD5=$(md5sum "$file" | awk '{print $1}')
	COMPARE_MD5="Not in DB"
	if [ -f "_db/$MD5" ]; then
		COMPARE_MD5=$(cat "_db/$MD5") 
	fi
	if [ ! "$FILE_MD5" == "$COMPARE_MD5" ]; then
		echo MISMATCH ${file##*/} $FILE_MD5 $COMPARE_MD5
		zopflipng -m --lossy_transparent "$file" temp.png
		mv temp.png "$file"
		echo $FILE_MD5 > _db/$MD5
	else
		echo SKIPPING $file
	fi
done